class FxData{
    constructor(){

    }

    fxNews(req, res){
        //Then res pnd let be my news api
        res.status(200).json(
          [  {
        
            id:1,
            pair:'GBP/USD',
            news:[{
              id:1,
              currency:'GBP',
              date:'Leo',
              time:'08:00PM',
              news:'Singapore Consumer Price Index (CPI) YoY',
              released:'Mar 23,2023 08:00',
              source:'Singapore Department of Statistics',
              previous:'6.6%',
              forecast:'6.5%',
              actual:'6.3%',
              sign:'red',
              description:`Kuwepo kwa pungozo la viwango kunatarajiwa bullish kwenye fedha ya GBP `,
            },
            {
              id:2,
              currency:'GBP',
              date:'kesho',
              time:'09:00PM',
              news:'Growth Rate Demostic Product(GDP)',
              released:'Mar 23,2023 08:00',
              source:'NAIURO',
              previous:'6.6%',
              forecast:'6.5%',
              actual:'7.3%',
              sign:'green',
              description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
            },
            {
              id:3,
              currency:'USD',
              date:'Leo',
              time:'09:00PM',
              news:'Unemproyment Rate',
              released:'Mar 23,2023 08:00',
              source:'Central Bank Of America',
              previous:'6.6%',
              forecast:'6.5%',
              actual:'7.3%',
              sign:'green',
              description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
            },
            {
              id:4,
              currency:'USD',
              date:'kesho',
              time:'10:00PM',
              news:'Trading Balance',
              released:'Mar 23,2023 08:00',
              source:'Central Bank Of America',
              previous:'6.6%',
              forecast:'6.5%',
              actual:'6.3%',
              sign:'red',
              description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
            }, 
          ],
          
     },

     {
        id:2,
        pair:'AUD/USD',
        news:[{
          id:1,
          currency:'AUD',
          date:'Leo',
          time:'08:00PM',
          news:'Singapore Consumer Price Index (CPI) YoY',
          released:'Mar 23,2023 08:00',
          source:'Singapore Department of Statistics',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bullish kwenye fedha ya GBP `,
        },
        {
          id:2,
          currency:'USD',
          date:'kesho',
          time:'09:00PM',
          news:'Growth Rate Demostic Product(GDP)',
          released:'Mar 23,2023 08:00',
          source:'NAIURO',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'7.3%',
          sign:'green',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        },
        {
          id:3,
          currency:'AUD',
          date:'Leo',
          time:'09:00PM',
          news:'Unemproyment Rate',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'7.3%',
          sign:'green',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        },
        {
          id:4,
          currency:'USD',
          date:'kesho',
          time:'10:00PM',
          news:'Trading Balance',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        }, 
      ],
      },
     
      {
        id:3,
        pair:'GBP/JPY',
        news:[{
          id:1,
          currency:'GBP',
          date:'Leo',
          time:'08:00PM',
          news:'Singapore Consumer Price Index (CPI) YoY',
          released:'Mar 23,2023 08:00',
          source:'Singapore Department of Statistics',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bullish kwenye fedha ya GBP `,
        },
        {
          id:2,
          currency:'JPY',
          date:'Leo',
          time:'09:00PM',
          news:'Growth Rate Demostic Product(GDP)',
          released:'Mar 23,2023 08:00',
          source:'NAIURO',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'7.3%',
          sign:'green',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        },
        {
          id:3,
          currency:'JPY',
          date:'kesho',
          time:'09:00PM',
          news:'Unemproyment Rate',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'7.3%',
          sign:'green',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        },
        {
          id:4,
          currency:'GBP',
          date:'Leo',
          time:'10:00PM',
          news:'Trading Balance',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        }, 
      ],
      },

      
      {
        id:4,
        pair:'USD/CAD',
        news:[{
          id:1,
          currency:'CAD',
          date:'Leo',
          time:'08:00PM',
          news:'Singapore Consumer Price Index (CPI) YoY',
          released:'Mar 23,2023 08:00',
          source:'Singapore Department of Statistics',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bullish kwenye fedha ya GBP `,
        },
        {
          id:2,
          currency:'USD',
          date:'Leo',
          time:'09:00PM',
          news:'Growth Rate Demostic Product(GDP)',
          released:'Mar 23,2023 08:00',
          source:'NAIURO',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'7.3%',
          sign:'green',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        },
        {
          id:3,
          currency:'USD',
          date:'Leo',
          time:'09:00PM',
          news:'Unemproyment Rate',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'7.3%',
          sign:'green',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        },
        {
          id:4,
          currency:'CAD',
          date:'Leo',
          time:'10:00PM',
          news:'Trading Balance',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        }, 
        {
          id:5,
          currency:'CAD',
          date:'Leo',
          time:'10:00PM',
          news:'Trading Balance',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        }, 
        {
          id:6,
          currency:'CAD',
          date:'Leo',
          time:'10:00PM',
          news:'Trading Balance',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        }, 
        {
          id:7,
          currency:'CAD',
          date:'Leo',
          time:'10:00PM',
          news:'Trading Balance',
          released:'Mar 23,2023 08:00',
          source:'Central Bank Of America',
          previous:'6.6%',
          forecast:'6.5%',
          actual:'6.3%',
          sign:'red',
          description:`Kuwepo kwa pungozo la viwango kunatarajiwa bearish kwenye fedha ya GBP `,
        }, 
      ],
      }
     
     
    ] )
    }
}

module.exports = new FxData()