class FxData{
  constructor(){

  }

  fxNews(req, res){
      //Then res pnd let be my news api
      res.status(200).json(
        [  {
      
          id:1,
          pair:'GBP/USD',
          news:[{
            id:1,
            currency:'GBP',
            date:'Leo',
            time:'09:00AM',
            news:'United Kingdom Trade Balance',
            released:'Jun 14,2023 09:00',
            source:'Office for National Statistics',
            previous:'-16.36B',
            forecast:'-16.50B',
            actual:'-15.00B',
            sign:'green',
            description:`Trade Balance measure the difference in value between imported and exported goods. A postive number indicates that
            more goods and services were exported than imported`,
          },
          {
            id:2,
            currency:'GBP',
            date:'Leo',
            time:'09:00AM',
            news:'United Kingdom Industrial',
            released:'Jun 14,2023 09:00',
            source:'Office for National Statistics',
            previous:'0.7%',
            forecast:'-0.1%',
            actual:'-0.3%',
            sign:'red',
            description:`Industrial Production measure the changes in the total inflation-adjusted value of output
            produced by manufactures,mines,and utilities`,
          },
          {
            id:3,
            currency:'USD',
            date:'kesho',
            time:'15:30PM',
            news:'United State Core Retails Sales MOM',
            released:'May 16,2023 15:00',
            source:'Census Bureau',
            previous:'-0.5%',
            forecast:'0.4%',
            actual:'0.4%',
            sign:'green',
            description:`Core Retails Sales measures the change in the total value of sales at the retails in the U.S excluding automobiles`,
          },
          {
            id:4,
            currency:'USD',
            date:'kesho',
            time:'15:30PM',
            news:'United State initial Jobless Claims',
            released:'Jun 08,2023 15:00',
            source:'Depertment of Labor',
            previous:'233k',
            forecast:'235k',
            actual:'261k',
            sign:'red',
            description:`Initial Jobless Claims measures the number of individualss who filed for unemployment insurancy 
            for the first time during the past week`,
          },
          {
            id:5,
            currency:'USD',
            date:'kesho',
            time:'15:30PM',
            news:'United States Philadelphia Federal Reserve Manufacturing index',
            released:'Jun 08,2023 15:00',
            source:'Federal Reserve Bank of philadelphia',
            previous:'-31.3',
            forecast:'-19.8',
            actual:'-10.4',
            sign:'green',
            description:`The Philadelphia Federal Reserve Manufacturing index rates the relative level of general business condition`,
          },
          {
            id:6,
            currency:'USD',
            date:'Leo',
            time:'11:00AM',
            news:'IEA Monthly Report',
            released:'May 16,2023 11:00',
            source:'IEA',
            previous:'6.6%',
            forecast:'6.5%',
            actual:'7.3%',
            sign:'green',
            description:`The International Energy Agency Monthly Oil Market Report covers major issues affecting
            the world oil market and provides an outlook for crude oil market developments for the comming year`,
          },
          {
            id:7,
            currency:'USD',
            date:'Leo',
            time:'15:30PM',
            news:'United States Producer Price Index (PPI) MoM',
            released:'May 11,2023 15:00',
            source:'U.S Bureau of Labor Statistics Department of Labor',
            previous:'-0.4%',
            forecast:'0.3%',
            actual:'0.2%',
            sign:'red',
            description:`The producer Price Index(PPI) measures the change in the price of goods sold by manufactures`,
          }, 
          {
            id:8,
            currency:'USD',
            date:'Leo',
            time:'17:30PM',
            news:'United States Crude Oil Inventories',
            released:'May 11,2023 15:00',
            source:'Energy Information Administration',
            previous:'4.488M',
            forecast:'1.022M',
            actual:'-0.451M',
            sign:'green',
            description:`Energy Information Administration's(EIA) Crude Oil Inventories measure the weekly change in the 
            number of barrels of commercial crude oil held by US firms.`,
          }, 
          {
            id:9,
            currency:'USD',
            date:'Leo',
            time:'15:30PM',
            news:'U.S Federal Reserve (Fed) Economic Projectios',
            released:'Mar 3,2023 21:00',
            source:'Federal Reserve',
            previous:'-0.4%',
            forecast:'0.3%',
            actual:'0.2%',
            sign:'green',
            description:`This report includes the Federal Open Market Committee's(FOMC) projectio for inflation and econo,ic growth`,
          }, 
        ],
        
   },

   {
      id:2,
      pair:'AUD/USD',
      news:[
        {
        id:1,
        currency:'AUD',
        date:'kesho',
        time:'04:30PM',
        news:'Australia Unemployment Rate',
        released:'May 18,2023 04:30',
        source:'Australia Bureau of Statistics',
        previous:'3.6%',
        forecast:'3.5%',
        actual:'3.7%',
        sign:'red',
        description:`The unemployment Rate measure the percentage of the total work force that is unemployed and actively seeking employment during the previous month`,
      },
      {
        id:2,
        currency:'AUD',
        date:'kesho',
        time:'14:30PM',
        news:'Australia Full Employment Change',
        released:'May 18,2023 14:30',
        source:'Australia Bureau of Statistics',
        previous:'82.5K',
        forecast:'',
        actual:'27.1K',
        sign:'green',
        description:`This describe the situation in which all available labor resource are being used in the most economically efficient`,
      },
      {
        id:3,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United State Core Retails Sales MOM',
        released:'May 16,2023 15:00',
        source:'Census Bureau',
        previous:'-0.5%',
        forecast:'0.4%',
        actual:'0.4%',
        sign:'green',
        description:`Core Retails Sales measures the change in the total value of sales at the retails in the U.S excluding automobiles`,
      },
      {
        id:4,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United State initial Jobless Claims',
        released:'Jun 08,2023 15:00',
        source:'Depertment of Labor',
        previous:'233k',
        forecast:'235k',
        actual:'261k',
        sign:'red',
        description:`Initial Jobless Claims measures the number of individualss who filed for unemployment insurancy 
        for the first time during the past week`,
      },
      {
        id:5,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United States Philadelphia Federal Reserve Manufacturing index',
        released:'Jun 08,2023 15:00',
        source:'Federal Reserve Bank of philadelphia',
        previous:'-31.3',
        forecast:'-19.8',
        actual:'-10.4',
        sign:'green',
        description:`The Philadelphia Federal Reserve Manufacturing index rates the relative level of general business condition`,
      },
      {
        id:6,
        currency:'USD',
        date:'Leo',
        time:'11:00AM',
        news:'IEA Monthly Report',
        released:'May 16,2023 11:00',
        source:'IEA',
        previous:'6.6%',
        forecast:'6.5%',
        actual:'7.3%',
        sign:'green',
        description:`The International Energy Agency Monthly Oil Market Report covers major issues affecting
        the world oil market and provides an outlook for crude oil market developments for the comming year`,
      },
      {
        id:7,
        currency:'USD',
        date:'Leo',
        time:'15:30PM',
        news:'United States Producer Price Index (PPI) MoM',
        released:'May 11,2023 15:00',
        source:'U.S Bureau of Labor Statistics Department of Labor',
        previous:'-0.4%',
        forecast:'0.3%',
        actual:'0.2%',
        sign:'red',
        description:`The producer Price Index(PPI) measures the change in the price of goods sold by manufactures`,
      }, 
      {
        id:8,
        currency:'USD',
        date:'Leo',
        time:'17:30PM',
        news:'United States Crude Oil Inventories',
        released:'May 11,2023 15:00',
        source:'Energy Information Administration',
        previous:'4.488M',
        forecast:'1.022M',
        actual:'-0.451M',
        sign:'green',
        description:`Energy Information Administration's(EIA) Crude Oil Inventories measure the weekly change in the 
        number of barrels of commercial crude oil held by US firms.`,
      }, 
      {
        id:9,
        currency:'USD',
        date:'Leo',
        time:'15:30PM',
        news:'U.S Federal Reserve (Fed) Economic Projectios',
        released:'Mar 3,2023 21:00',
        source:'Federal Reserve',
        previous:'-0.4%',
        forecast:'0.3%',
        actual:'0.2%',
        sign:'green',
        description:`This report includes the Federal Open Market Committee's(FOMC) projectio for inflation and econo,ic growth`,
      }, 
    ],
    },
   
    {
      id:3,
      pair:'GBP/JPY',
      news:[{
        id:1,
        currency:'GBP',
        date:'Leo',
        time:'09:00AM',
        news:'United Kingdom Trade Balance',
        released:'Jun 14,2023 09:00',
        source:'Office for National Statistics',
        previous:'-16.36B',
        forecast:'-16.50B',
        actual:'-15.00B',
        sign:'green',
        description:`Trade Balance measure the difference in value between imported and exported goods. A postive number indicates that
        more goods and services were exported than imported`,
      },
      {
        id:2,
        currency:'GBP',
        date:'Leo',
        time:'09:00AM',
        news:'United Kingdom Industrial',
        released:'Jun 14,2023 09:00',
        source:'Office for National Statistics',
        previous:'0.7%',
        forecast:'-0.1%',
        actual:'-0.3%',
        sign:'red',
        description:`Industrial Production measure the changes in the total inflation-adjusted value of output
        produced by manufactures,mines,and utilities`,
      },
      {
        id:3,
        currency:'JPY',
        date:'kesho',
        time:'02:50AM',
        news:'Japan Trade Balance',
        released:'Mar 23,2023 08:00',
        source:'Ministry of Finance',
        previous:'-755.1B',
        forecast:'-613.8B',
        actual:'-432.4B',
        sign:'green',
        description:`This measures the difference in value between imported and exported goods and services over time`,
      },
      {
        id:4,
        currency:'JPY',
        date:'kesho',
        time:'02:50AM',
        news:'Japan Trade Balance',
        released:'Mar 23,2023 08:00',
        source:'Ministry of Finance',
        previous:'4.3%',
        forecast:'3.0%',
        actual:'2.6%',
        sign:'red',
        description:`This Exports number provides the total US doller amount of merchandise exports on f.o.b`,
      },
      {
        id:5,
        currency:'JPY',
        date:'Leo',
        time:'07:30AM',
        news:'Japan Tertiary Industy Activity Index MoM',
        released:'Mar 23,2023 08:00',
        source:'METI',
        previous:'1.7%',
        forecast:'0.3%',
        actual:'-1.7%',
        sign:'red',
        description:`This Tertialy Industry Index measure the change in the total value of service purchased by businesses.`,
      }, 
    ],
    },

    
    {
      id:4,
      pair:'USD/CAD',
      news:[
        {
        id:1,
        currency:'CAD',
        date:'kesho',
        time:'15:15PM',
        news:'Canada Housing Starts',
        released:'May 15,2023 15:15',
        source:'Canadian Mortgage and Housing Corporation',
        previous:'213.8K',
        forecast:'224.6K',
        actual:'261.6K',
        sign:'green',
        description:`This starts measures the changes in the annualized number of new residential buildings`,
      },
        {
        id:2,
        currency:'CAD',
        date:'kesho',
        time:'15:20PM',
        news:'Canada Manufacturing Sales MoM',
        released:'May 25,2023 15:15',
        source:'Canadian Mortgage and Housing Corporation',
        previous:'0.7%',
        forecast:'',
        actual:'-0.2%',
        sign:'red',
        description:`Manufacturing Sales measures the change in the overall value pf sales made at the manufacturing sector`,
      },
      {
        id:3,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United State Core Retails Sales MOM',
        released:'May 16,2023 15:00',
        source:'Census Bureau',
        previous:'-0.5%',
        forecast:'0.4%',
        actual:'0.4%',
        sign:'green',
        description:`Core Retails Sales measures the change in the total value of sales at the retails in the U.S excluding automobiles`,
      },
      {
        id:4,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United State initial Jobless Claims',
        released:'Jun 08,2023 15:00',
        source:'Depertment of Labor',
        previous:'233k',
        forecast:'235k',
        actual:'261k',
        sign:'red',
        description:`Initial Jobless Claims measures the number of individualss who filed for unemployment insurancy 
        for the first time during the past week`,
      },
      {
        id:5,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United States Philadelphia Federal Reserve Manufacturing index',
        released:'Jun 08,2023 15:00',
        source:'Federal Reserve Bank of philadelphia',
        previous:'-31.3',
        forecast:'-19.8',
        actual:'-10.4',
        sign:'green',
        description:`The Philadelphia Federal Reserve Manufacturing index rates the relative level of general business condition`,
      },
      {
        id:6,
        currency:'USD',
        date:'Leo',
        time:'11:00AM',
        news:'IEA Monthly Report',
        released:'May 16,2023 11:00',
        source:'IEA',
        previous:'6.6%',
        forecast:'6.5%',
        actual:'7.3%',
        sign:'green',
        description:`The International Energy Agency Monthly Oil Market Report covers major issues affecting
        the world oil market and provides an outlook for crude oil market developments for the comming year`,
      },
      {
        id:7,
        currency:'USD',
        date:'Leo',
        time:'15:30PM',
        news:'United States Producer Price Index (PPI) MoM',
        released:'May 11,2023 15:00',
        source:'U.S Bureau of Labor Statistics Department of Labor',
        previous:'-0.4%',
        forecast:'0.3%',
        actual:'0.2%',
        sign:'red',
        description:`The producer Price Index(PPI) measures the change in the price of goods sold by manufactures`,
      }, 
      {
        id:8,
        currency:'USD',
        date:'Leo',
        time:'17:30PM',
        news:'United States Crude Oil Inventories',
        released:'May 11,2023 15:00',
        source:'Energy Information Administration',
        previous:'4.488M',
        forecast:'1.022M',
        actual:'-0.451M',
        sign:'green',
        description:`Energy Information Administration's(EIA) Crude Oil Inventories measure the weekly change in the 
        number of barrels of commercial crude oil held by US firms.`,
      }, 
      {
        id:9,
        currency:'USD',
        date:'Leo',
        time:'15:30PM',
        news:'U.S Federal Reserve (Fed) Economic Projectios',
        released:'Mar 3,2023 21:00',
        source:'Federal Reserve',
        previous:'-0.4%',
        forecast:'0.3%',
        actual:'0.2%',
        sign:'green',
        description:`This report includes the Federal Open Market Committee's(FOMC) projectio for inflation and econo,ic growth`,
      }, 
    ],
    },
    {
      id:5,
      pair:'EUR/USD',
      news:[
        {
        id:1,
        currency:'EUR',
        date:'Leo',
        time:'12:00PM',
        news:'European Industrial production MoM',
        released:'May 15,2023 12:00',
        source:'Eurostat',
        previous:'1.5%',
        forecast:'-2.5%',
        actual:'-4.1%',
        sign:'red',
        description:`This measure the change in the total inflation-adjusted value of output produced by manufactures,mine and utilities`,
      },
        {
        id:2,
        currency:'EUR',
        date:'Leo',
        time:'12:30PM',
        news:'Germany 10-Year Bond Auction',
        released:'May 25,2023 12:30',
        source:'Communications Depertment',
        previous:'2.510%',
        forecast:'',
        actual:'2.310%',
        sign:'red',
        description:`The figures displayed in the calender represent the average yield on the Bund auctioned`,
      },
        {
        id:3,
        currency:'EUR',
        date:'kesho',
        time:'09:45AM',
        news:'Frence Consumer Price Index(CPI) MoM',
        released:'May 31,2023 09:45',
        source:'French National Institute for Statistics',
        previous:'0.6%',
        forecast:'0.4%',
        actual:'-0.1%',
        sign:'red',
        description:`This measure the changes in the price of goods and service purchased by consumers`,
      },
        {
        id:4,
        currency:'EUR',
        date:'kesho',
        time:'09:45AM',
        news:'Frence Harmonised Index of Consumer prices(HICP) MoM',
        released:'May 31,2023 09:45',
        source:'Insee',
        previous:'0.6%',
        forecast:'0.4%',
        actual:'-0.1%',
        sign:'red',
        description:`Is the same as CPI, but with a joint basket of products for all Eurozone member countries `,
      },
      {
        id:5,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United State Core Retails Sales MOM',
        released:'May 16,2023 15:00',
        source:'Census Bureau',
        previous:'-0.5%',
        forecast:'0.4%',
        actual:'0.4%',
        sign:'green',
        description:`Core Retails Sales measures the change in the total value of sales at the retails in the U.S excluding automobiles`,
      },
      {
        id:6,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United State initial Jobless Claims',
        released:'Jun 08,2023 15:00',
        source:'Depertment of Labor',
        previous:'233k',
        forecast:'235k',
        actual:'261k',
        sign:'red',
        description:`Initial Jobless Claims measures the number of individualss who filed for unemployment insurancy 
        for the first time during the past week`,
      },
      {
        id:7,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United States Philadelphia Federal Reserve Manufacturing index',
        released:'Jun 08,2023 15:00',
        source:'Federal Reserve Bank of philadelphia',
        previous:'-31.3',
        forecast:'-19.8',
        actual:'-10.4',
        sign:'green',
        description:`The Philadelphia Federal Reserve Manufacturing index rates the relative level of general business condition`,
      },
      {
        id:8,
        currency:'USD',
        date:'Leo',
        time:'11:00AM',
        news:'IEA Monthly Report',
        released:'May 16,2023 11:00',
        source:'IEA',
        previous:'6.6%',
        forecast:'6.5%',
        actual:'7.3%',
        sign:'green',
        description:`The International Energy Agency Monthly Oil Market Report covers major issues affecting
        the world oil market and provides an outlook for crude oil market developments for the comming year`,
      },
      {
        id:9,
        currency:'USD',
        date:'Leo',
        time:'15:30PM',
        news:'United States Producer Price Index (PPI) MoM',
        released:'May 11,2023 15:00',
        source:'U.S Bureau of Labor Statistics Department of Labor',
        previous:'-0.4%',
        forecast:'0.3%',
        actual:'0.2%',
        sign:'red',
        description:`The producer Price Index(PPI) measures the change in the price of goods sold by manufactures`,
      }, 
      {
        id:10,
        currency:'USD',
        date:'Leo',
        time:'17:30PM',
        news:'United States Crude Oil Inventories',
        released:'May 11,2023 15:00',
        source:'Energy Information Administration',
        previous:'4.488M',
        forecast:'1.022M',
        actual:'-0.451M',
        sign:'green',
        description:`Energy Information Administration's(EIA) Crude Oil Inventories measure the weekly change in the 
        number of barrels of commercial crude oil held by US firms.`,
      }, 
      {
        id:11,
        currency:'USD',
        date:'Leo',
        time:'15:30PM',
        news:'U.S Federal Reserve (Fed) Economic Projectios',
        released:'Mar 3,2023 21:00',
        source:'Federal Reserve',
        previous:'-0.4%',
        forecast:'0.3%',
        actual:'0.2%',
        sign:'green',
        description:`This report includes the Federal Open Market Committee's(FOMC) projectio for inflation and econo,ic growth`,
      }, 
    ],
    },
    {
      id:6,
      pair:'USX/JPY',
      news:[
        {
          id:1,
          currency:'JPY',
          date:'kesho',
          time:'02:50AM',
          news:'Japan Trade Balance',
          released:'Mar 23,2023 08:00',
          source:'Ministry of Finance',
          previous:'-755.1B',
          forecast:'-613.8B',
          actual:'-432.4B',
          sign:'green',
          description:`This measures the difference in value between imported and exported goods and services over time`,
        },
        {
          id:2,
          currency:'JPY',
          date:'kesho',
          time:'02:50AM',
          news:'Japan Trade Balance',
          released:'Mar 23,2023 08:00',
          source:'Ministry of Finance',
          previous:'4.3%',
          forecast:'3.0%',
          actual:'2.6%',
          sign:'red',
          description:`This Exports number provides the total US doller amount of merchandise exports on f.o.b`,
        },
        {
          id:3,
          currency:'JPY',
          date:'Leo',
          time:'07:30AM',
          news:'Japan Tertiary Industy Activity Index MoM',
          released:'Mar 23,2023 08:00',
          source:'METI',
          previous:'1.7%',
          forecast:'0.3%',
          actual:'-1.7%',
          sign:'red',
          description:`This Tertialy Industry Index measure the change in the total value of service purchased by businesses.`,
        }, 
      {
        id:5,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United State Core Retails Sales MOM',
        released:'May 16,2023 15:00',
        source:'Census Bureau',
        previous:'-0.5%',
        forecast:'0.4%',
        actual:'0.4%',
        sign:'green',
        description:`Core Retails Sales measures the change in the total value of sales at the retails in the U.S excluding automobiles`,
      },
      {
        id:6,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United State initial Jobless Claims',
        released:'Jun 08,2023 15:00',
        source:'Depertment of Labor',
        previous:'233k',
        forecast:'235k',
        actual:'261k',
        sign:'red',
        description:`Initial Jobless Claims measures the number of individualss who filed for unemployment insurancy 
        for the first time during the past week`,
      },
      {
        id:7,
        currency:'USD',
        date:'kesho',
        time:'15:30PM',
        news:'United States Philadelphia Federal Reserve Manufacturing index',
        released:'Jun 08,2023 15:00',
        source:'Federal Reserve Bank of philadelphia',
        previous:'-31.3',
        forecast:'-19.8',
        actual:'-10.4',
        sign:'green',
        description:`The Philadelphia Federal Reserve Manufacturing index rates the relative level of general business condition`,
      },
      {
        id:8,
        currency:'USD',
        date:'Leo',
        time:'11:00AM',
        news:'IEA Monthly Report',
        released:'May 16,2023 11:00',
        source:'IEA',
        previous:'6.6%',
        forecast:'6.5%',
        actual:'7.3%',
        sign:'green',
        description:`The International Energy Agency Monthly Oil Market Report covers major issues affecting
        the world oil market and provides an outlook for crude oil market developments for the comming year`,
      },
      {
        id:9,
        currency:'USD',
        date:'Leo',
        time:'15:30PM',
        news:'United States Producer Price Index (PPI) MoM',
        released:'May 11,2023 15:00',
        source:'U.S Bureau of Labor Statistics Department of Labor',
        previous:'-0.4%',
        forecast:'0.3%',
        actual:'0.2%',
        sign:'red',
        description:`The producer Price Index(PPI) measures the change in the price of goods sold by manufactures`,
      }, 
      {
        id:10,
        currency:'USD',
        date:'Leo',
        time:'17:30PM',
        news:'United States Crude Oil Inventories',
        released:'May 11,2023 15:00',
        source:'Energy Information Administration',
        previous:'4.488M',
        forecast:'1.022M',
        actual:'-0.451M',
        sign:'green',
        description:`Energy Information Administration's(EIA) Crude Oil Inventories measure the weekly change in the 
        number of barrels of commercial crude oil held by US firms.`,
      }, 
      {
        id:11,
        currency:'USD',
        date:'Leo',
        time:'15:30PM',
        news:'U.S Federal Reserve (Fed) Economic Projectios',
        released:'Mar 3,2023 21:00',
        source:'Federal Reserve',
        previous:'-0.4%',
        forecast:'0.3%',
        actual:'0.2%',
        sign:'green',
        description:`This report includes the Federal Open Market Committee's(FOMC) projectio for inflation and econo,ic growth`,
      }, 
    ],
    },
    {
      id:7,
      pair:'AUD/JPY',
      news:[
        {
          id:1,
          currency:'JPY',
          date:'kesho',
          time:'02:50AM',
          news:'Japan Trade Balance',
          released:'Mar 23,2023 08:00',
          source:'Ministry of Finance',
          previous:'-755.1B',
          forecast:'-613.8B',
          actual:'-432.4B',
          sign:'green',
          description:`This measures the difference in value between imported and exported goods and services over time`,
        },
        {
          id:2,
          currency:'JPY',
          date:'kesho',
          time:'02:50AM',
          news:'Japan Trade Balance',
          released:'Mar 23,2023 08:00',
          source:'Ministry of Finance',
          previous:'4.3%',
          forecast:'3.0%',
          actual:'2.6%',
          sign:'red',
          description:`This Exports number provides the total US doller amount of merchandise exports on f.o.b`,
        },
        {
          id:3,
          currency:'JPY',
          date:'Leo',
          time:'07:30AM',
          news:'Japan Tertiary Industy Activity Index MoM',
          released:'Mar 23,2023 08:00',
          source:'METI',
          previous:'1.7%',
          forecast:'0.3%',
          actual:'-1.7%',
          sign:'red',
          description:`This Tertialy Industry Index measure the change in the total value of service purchased by businesses.`,
        }, 
        {
          id:4,
          currency:'AUD',
          date:'kesho',
          time:'04:30PM',
          news:'Australia Unemployment Rate',
          released:'May 18,2023 04:30',
          source:'Australia Bureau of Statistics',
          previous:'3.6%',
          forecast:'3.5%',
          actual:'3.7%',
          sign:'red',
          description:`The unemployment Rate measure the percentage of the total work force that is unemployed and actively seeking employment during the previous month`,
        },
        {
          id:5,
          currency:'AUD',
          date:'kesho',
          time:'14:30PM',
          news:'Australia Full Employment Change',
          released:'May 18,2023 14:30',
          source:'Australia Bureau of Statistics',
          previous:'82.5K',
          forecast:'',
          actual:'27.1K',
          sign:'green',
          description:`This describe the situation in which all available labor resource are being used in the most economically efficient`,
        },
    ],
    },
   
   
  ] )
  }
}

module.exports = new FxData()